---
label: Design Settings
hide_body: true
fields:
- name: primary_color
  type: color
  label: Info Page - Background Color
  config:
    required: false
    color_format: Hex
  description: Adjust the background color of the info page
  default: "#B1BCBC"
- name: text_color
  type: color
  label: Info Page - Text Color
  config:
    required: false
    color_format: Hex
  description: Enter text color for info page
- name: test
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: ''
  label: Test
pages:
- my-directory/wowza.md
- themes/tale-theme/data/Settings.toml
